apiVersion: v1
kind: Namespace
metadata:
  name: octopus-{{ .Values.env }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: octopus-{{ .Values.env }}-sa
  namespace: octopus-{{ .Values.env }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: octopus-{{ .Values.env }}
  name: octopus-{{ .Values.env }}-sa-role
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["deployments", "replicasets", "pods", "services", "ingresses", "secrets", "configmaps"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get"]     
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: octopus-{{ .Values.env }}-sa-binding
  namespace: octopus-{{ .Values.env }}
subjects:
- kind: ServiceAccount
  name: octopus-{{ .Values.env }}-sa
  apiGroup: ""
roleRef:
  kind: Role
  name: octopus-{{ .Values.env }}-sa-role
  apiGroup: ""
