---
apiVersion: v1
kind: Service
metadata:
  name: webapp-color-service
spec:
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: {{ .Values.env.PORT }}
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    name: webapp
  sessionAffinity: None
  type: NodePort